### ISSUE TITLE
deploy to /conferences/2024 ?

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwlcon2024#1]
Configure a GitHub action to render HTML and publish to https://github.com/common-workflow-language/common-workflow-language.github.io under a `conferences/2024` subfolder using the https://github.com/cwl-bot

**Comment by mr-c** [comment]
The deploy logic https://github.com/common-workflow-language/cwl-website/blob/4196f737bab3469587a7db7ab9259db88672642d/.github/workflows/deploy.yml#L36-L47

**Comment by alexiswl** [comment]
@mr-c I have a local branch ready to push. Would you prefer a PR over a fork or from a branch within this repo?

**Comment by mr-c** [comment]
> @mr-c I have a local branch ready to push. Would you prefer a PR over a fork or from a branch within this repo?

Either is fine, thanks!
