### ISSUE TITLE
Form submission page

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwlcon2024#10]
Just need a URL to put in the invitations

can just say "Submissions will open in February" or similar

**Comment by alexiswl** [comment]
Will https://www.commonwl.org/conferences/2024/ suffice as the link for now?

**Comment by alexiswl** [comment]
Related https://github.com/common-workflow-language/cwl-website/pull/187

**Comment by alexiswl** [comment]
Is Google Forms appropriate? Happy to draft something up before the next meeting
