### ISSUE TITLE
Date and location attributes render too closely

### ISSUE THREAD

**Issue by alexiswl** [common-workflow-language/cwlcon2024#18]
See here

![image](https://github.com/common-workflow-language/cwlcon2024/assets/8197659/911d62fa-2926-440c-a21c-8629dd19f4f9)

@kinow can I assign you to fix this, will be much faster than me learning CSS

**Comment by kinow** [comment]
Sure thing @alexiswl , I will have a look at this one, probably with @Fienne :tada:

**Comment by mr-c** [comment]
Oh, lets make it clear that the dates are not yet final (they may change +/- a few days), and that the conference is hybrid: Online & Netherlands

**Comment by tom-tan** [comment]
FYI: I can reproduce this issue with Chrome 120.0.6099.62 and Safari 17.1.2.
On the other hand, it works correctly with Firefox 120.0.1 as shown below:
<img width="461" alt="スクリーンショット 2023-12-08 17 31 39" src="https://github.com/common-workflow-language/cwlcon2024/assets/4450141/e93757cd-f97d-425c-aa73-70b0b2bd0b8f">

**Comment by kinow** [comment]
Thanks @tom-tan ! PR created :+1:
