### ISSUE TITLE
theming, use CWL logo and colors

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwlcon2024#2]
https://github.com/common-workflow-language/media

**Comment by alexiswl** [comment]
This wasn't easy... 

The CSS image only supports 1000 by 270ish and truncates the top part of the original picture (which is 1000 by 400)

So I've generated a 300 by 250 ish pxl CWL logo and placed that in bottom left part of a 1000 by 400 px image.

CSS is certainly not my forte.  

Here's the result though 

![image](https://github.com/common-workflow-language/cwlcon2024/assets/8197659/d6780913-291b-4f31-8bfb-87c42138729d)
