### ISSUE TITLE
Add link to previous conferences

### ISSUE THREAD

**Issue by kinow** [common-workflow-language/cwlcon2024#20]
From today's meeting.

**Comment by manabuishii** [comment]
CWLCon2021
https://pad.sfconservancy.org/p/CWLcon2021

CWLCon2022
https://cwl.discourse.group/t/2022-cwl-conference-feb-28-mar-4-2022/519

CWLCon2023
https://cwl.discourse.group/t/schedule-of-confirmed-talks/753

**Comment by kinow** [comment]
Thank you @manabuishii !!!
