### ISSUE TITLE
Training session/activities

### ISSUE THREAD

**Issue by kinow** [common-workflow-language/cwlcon2024#28]
We will have training in CWLCon24.

Preferably one session for online participants, and **another** one for in person. This is to avoid cases where the speakers are not able to support both online and in person, and to simplify how the session is given to the audience (one is planned for online, the other for in person).

**Comment by mr-c** [comment]
Who is interested in helping plan / teach / support the online training session?

**Comment by kinow** [comment]
I think @skanwal mentioned something about tutorials in a previous meeting, but I could be wrong.

**Comment by skanwal** [comment]
Happy to help with the online session.

**Comment by alexiswl** [comment]
Also happy to help set these up

**Comment by alexiswl** [comment]
@mr-c is just making the signup sheet now, will add a link on the website as soon as possible.  

@skanwal we will need a separate signup sheet for the APAC tutorial
