### ISSUE TITLE
invites to authors of recently published CWL papers (zotero)

### ISSUE THREAD

**Issue by kinow** [common-workflow-language/cwlcon2024#5]
The task is about inviting authors of recently published papers in an export made by Michael. We can check if there are any newer papers too, and prepare a template email to be sent to the authors.

**Comment by kinow** [comment]
I searched for CWL on Zenodo and it returned 118 results, the spreadsheet has 127, all but one from 2022. @mr-c is that spreadsheet from Google Search + Zenodo? If so I will try to update it with articles/presentations published in 2023 too.

Also, I was going to start a template to be sent to invite the author(s), but maybe we could reuse #7 ?

**Comment by mr-c** [comment]
Zenodo? Oh, I meant Zotero. Where we collect citations and other mentions of the CWL project

https://www.zotero.org/groups/2294829/cwl/library

**Comment by kinow** [comment]
Ah! I think you said it but I heard Zenodo :laughing: :laughing: :laughing:

**Comment by mr-c** [comment]
@kinow lets find a time to work together on this

**Comment by mr-c** [comment]
Instructions:
Go to https://docs.google.com/spreadsheets/d/1h6GA88y6LZDV3Ug_oo5HnZfhA_1CcNN-vMWbpM_23o0/edit#gid=668308611

Highlight 5 rows and change the background color to one of your choosing to reserve them for yourself. Evaluate the suitability for a direct invitation; feel free to ignore papers that just mention CWL briefly.

Put the status in the first column: 
- "NA" not applicable
- "invited by <name>" 
- "previous presenter"

**Comment by kinow** [comment]
Selected my first five (pink/rose). Will try to follow the guidelines and send the invites for those that have interesting publications related to CWL. Thanks a ton! Will send some other PR's/issues for what I can help with. Sorry the hiatus! :wave:

**Comment by kinow** [comment]
9 pending now. Will check tomorrow if there are any left that are easy to access/read/review/invite, but at least we already got some positive responses from authors considering to submit an EOI to give a talk. Let's hope we have a good selection of proposals this year! :sleeping_bed: :wave:
