### ISSUE TITLE
Used 'Google Form' twice

### ISSUE THREAD

**Issue by alexiswl** [common-workflow-language/cwlcon2024#56]
Rename each 'Google Form' to 'Talk Submission Form' and 'Registration Form' separately.  

It should also be noted to users that fill out the Talk Submission Form that they need to fill out the Registration form separately.

**Comment by skanwal** [comment]
Thinking how to best present this info to user i.e. "Call for submission" VS "Registration" - will it be helpful to have these both reflected in the main panel along with other tabs (Home Registration Program etc)?

**Comment by alexiswl** [comment]
Would you prefer something like this? Were we have a 'Submit a talk' on the main bar

![Screenshot 2024-02-28 at 2 46 26 pm](https://github.com/common-workflow-language/cwlcon2024/assets/8197659/879e42f4-fb48-4506-8816-0c1bde51edf4)

EXT

![image](https://github.com/common-workflow-language/cwlcon2024/assets/8197659/6e1b2041-a50a-438f-80c0-bd7ff68f0748)

**Comment by skanwal** [comment]
@alexiswl - Yes, having a separate tab for `Submit a talk` will serve the purpose. Thank you.

**Comment by alexiswl** [comment]
Resolved by #58
