### ISSUE TITLE
Add link to registration in abstract submission form

### ISSUE THREAD

**Issue by skanwal** [common-workflow-language/cwlcon2024#59]
Something like:

Have you registered for the conference:
- Yes
- No (please register here [link])

**Comment by alexiswl** [comment]
Let me just make sure it doesn't make a new link if I share it but will get this done at some point today

**Comment by alexiswl** [comment]
Done, updated with same link

![image](https://github.com/common-workflow-language/cwlcon2024/assets/8197659/5c4736a6-b3d7-420f-9325-7298462ae03a)
