### ISSUE TITLE
revise the top half

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwlcon2024#60]
1. Remove the red note in the upper right
2. Remove the “CWLCon 2024” redundant header
3. Add this text (possibly in boxes?) with links to the appropriate section of the detailed program

May 9th-11th Online Talks
Various timezones

May 15th In-person training
Amsterdam

May 15th-16th Conference
Amsterdam / Hybrid

May 17th Hackathon
Amsterdam

4. Add hyperlink to “▹Submissions are open and will close on Friday March 15, 2024 ◃”

**Comment by alexiswl** [comment]
> May 15th In-person training

Should be May 14th In-person training
