### ISSUE TITLE
Draft call for presentations

### ISSUE THREAD

**Issue by skanwal** [common-workflow-language/cwlcon2024#7]

**Comment by kinow** [comment]
Looks good to me! I think if we had the location + date + submission form that'd be 100% done, but we may have to submit it earlier without some of this info depending on how things go. Thanks @skanwal !

**Comment by alexiswl** [comment]
Looks good! And very well laid out too

> The [CWL](https://www.commonwl.org/) is a well-known and advocated standard for describing

I think we can change to 
_~~The~~ [CWL](https://www.commonwl.org/) is a well-known and advocated standard for describing_

> It has since been held online in the past two years.

Last year was a hybrid event.  

>  trianing sessions

~~trianing~~ training sessions

> The conference will feature contributed talks from speakers, vendors, trianing sessions and hackathon / collaboration-fest as well for profuse networking opportunities.

I think this sentence could be rearranged. We could either go _as well as profuse networking opportunities_ or split the sentence in to two. 

_The conference will feature ~~contributed~~ talks from speakers, vendors, training sessions and a hackathon / collaboration-fest.  
There will also be many networking opportunities at the conference._
